site_name: H5MD for NOMAD Schema
site_description: |
  NOMAD documentation describing how to adapt the H5MD schema for storing molecular dynamics data into a format suitable for upload to NOMAD.
site_author: FAIRmat consortium
nav:
  - Overview: index.md
  - File Structure:
    - Root: file_structure/root.md
    - H5MD: file_structure/h5md.md
    - Particles: file_structure/particles.md
    - Observables: file_structure/observables.md
    - Connectivity: file_structure/connectivity.md
    - Parameters: file_structure/parameters.md
  - Units: units.md
  - References:
    - Quick Start - H5MD basics: references/quick_H5MD_basics.md
    - Notable changes from H5MD to H5MD-NOMAD: references/unsupported.md
    - Standardized observables:
      - Configurational: references/standard_observables/configurational.md
      - Ensemble Average: references/standard_observables/ensemble_average.md
      - Time Correlation: references/standard_observables/time_correlation.md
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css

